create sequence addresses_seq start with 1 increment by 50;
create sequence persons_seq start with 1 increment by 50;
create sequence tests_seq start with 1 increment by 50;
create sequence teststations_seq start with 1 increment by 50;
create table addresses (id bigint not null, city varchar(255), country varchar(255), street_number varchar(255), version integer, zip_code varchar(255), primary key (id));
create table addresses_persons (address_id bigint not null, persons_id bigint not null, primary key (address_id, persons_id));
create table persons (id bigint not null, birth_date date not null, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), area_code integer, country_code integer, serial_number integer, ssn integer not null, version integer, address_id bigint, primary key (id));
create table persons_tests (person_id bigint not null, tests_id bigint not null, primary key (person_id, tests_id));
create table tests (id bigint not null, test_result varchar(255), test_bay integer, test_kit_type varchar(255), test_time_stamp timestamp(6) not null, version integer, person_id bigint, station_id bigint, primary key (id));
create table teststations (id bigint not null, station_name varchar(255), version integer, primary key (id));
alter table if exists addresses_persons add constraint UK_b8u23h96sdge0tmlcjtd6j317 unique (persons_id);
alter table if exists persons_tests add constraint UK_7miop10s4vsm27fsvay9wrn3m unique (tests_id);
alter table if exists addresses_persons add constraint FKlrm2a77hxdfvtan57gw6xc4eh foreign key (persons_id) references persons;
alter table if exists addresses_persons add constraint FKth7p2ug5jn3nnollf0hhjqm4x foreign key (address_id) references addresses;
alter table if exists persons add constraint FKhpk0ck378u9nar5y4b4cwb8sd foreign key (address_id) references addresses;
alter table if exists persons_tests add constraint FK6chfdtym4c5vpc2nogb54lu9b foreign key (tests_id) references tests;
alter table if exists persons_tests add constraint FKpk2txkw3bkolp23g107bqglqi foreign key (person_id) references persons;
alter table if exists tests add constraint FKniu0uhil0pfrjam8us6tf0g66 foreign key (person_id) references persons;
alter table if exists tests add constraint FKqguigcn5v92axcw5w3beum237 foreign key (station_id) references teststations;
